# Copyright 2024 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example mousekeyspr'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["totem_tp_left, totem_tp_right"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y"]'
      branches: '["zmkfirmware/zmk/main infused-kim/kb_zmk_ps2_mouse_trackpoint_driver/main"]'
