# Copyright 2024 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build totem with mousekeyspr'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["totem_left, totem_right"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y\nCONFIG_ZMK_MOUSE=y"]'
      branches: '["petejohanson/zmk/feat/pointers-move-scroll"]'